@startuml
package exercise3{
package movevalidator {
class MoveIsDiagonal
class MoveIsForward
class MoveLength
class MoveValidator
class NoOtherJumpMovePossible
class OpponentPieceBetweenJump
class StartPieceValid
class TargetFieldEmpty
}
class Board
class BoardPrinter
class GameLogic
class Move
class Piece
enum Player
class WinCondition
}
movevalidator ..> Board
movevalidator ..> Move
movevalidator ..> Piece
movevalidator ..> Player
GameLogic ..> BoardPrinter
GameLogic ..> Board
GameLogic ..> WinCondition
GameLogic ..> Move
GameLogic ..> Piece
GameLogic ..> Player
GameLogic ..> MoveValidator
GameLogic ..> NoOtherJumpMovePossible
WinCondition ..> MoveValidator
@enduml