@startuml


autonumber
loop while there is no winner
    GameLogic -> BoardPrinter: Print Board
    BoardPrinter -> Board: GetPieceAt
    Board -> BoardPrinter: Return piece
    GameLogic -> Move: Parse Input
    GameLogic <- Move: Either valid move or exception
    GameLogic -> Board: Get piece at start coordinates
    Board -> GameLogic: Either is empty or returns piece
    GameLogic -> MoveValidator: Check if move is valid
    MoveValidator -> GameLogic: Move is valid / not valid
    GameLogic -> Board: Execute move
    GameLogic -> WinCondition: Has the current player won?
    WinCondition -> GameLogic: Player has won / not won
    GameLogic -> Board: Get piece at end coordinates
    Board -> GameLogic: Either is empty or returns piece
    GameLogic -> MoveValidator: Check if no other jump move is possible
    MoveValidator -> GameLogic: Another jump move is possible / not possible
end

@enduml